name: "Pull Request Labeler"
on:
- pull_request
test-apis-dataUploadTest:
- ./**/*

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"